apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: default
spec:
  destination:
    namespace: sample-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment
    repoURL: https://github.com/titan-syndicate/echo-deployment/
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true