apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../base
# - ./argocd-crd.yaml
patches:
- path: argocd-server-command.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-server